[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sollong_ido = ""

[programs.devnet]
sollong_ido = ""

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#cluster = "testnet"
cluster = "devnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000